### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by hmyang0727** [kkang831/BDInvert_Release#1]
https://github.com/kkang831/BDInvert_Release/blob/5d1a20af8264033981991dc095dc3137224b5d17/BDInvert/train_basecode_encoder.py#L66

There is a minor typo on the line that I've quoted above.

A single apostrophe at the end of the line needs to be removed in order to run the code.

**Comment by kkang831** [comment]
Oh, thank you There was a mistake.
