### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by loboere** [kkang831/BDInvert_Release#2]
!python /content/BDInvert_Release/BDInvert/invert.py --encoder_pt_path /content/test/test.list

```

[autoreload of tqdm.std failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
ImportError: cannot import name 'WeakSet' from 'tqdm.utils' (/usr/local/lib/python3.7/dist-packages/tqdm/utils.py)
]
/usr/lib/python3.7/importlib/__init__.py:169: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  _bootstrap._exec(spec, module)
Building generator for model `stylegan2_ffhq1024` ...
Finish building generator.
Loading StyleGAN checkpoint from `checkpoints/stylegan2_ffhq1024.pth` ...
Finish loading StyleGAN checkpoint.
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/lib/python3.7/dist-packages/lpips/weights/v0.1/vgg.pth
basecode_layer :  x03
Encoder input shape  = [3, 128, 128]
Encoder output shape = torch.Size([512, 16, 16])
StyleGAN BaseCode Encoder Architecture
Sequential(
  (0): Conv2d(3, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): LeakyReLU(negative_slope=0.2, inplace=True)
  (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (5): LeakyReLU(negative_slope=0.2, inplace=True)
  (6): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (7): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (8): LeakyReLU(negative_slope=0.2, inplace=True)
  (9): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (12): LeakyReLU(negative_slope=0.2, inplace=True)
  (13): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (14): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (15): LeakyReLU(negative_slope=0.2, inplace=True)
  (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (17): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (18): LeakyReLU(negative_slope=0.2, inplace=True)
  (19): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (20): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (21): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (22): LeakyReLU(negative_slope=0.2, inplace=True)
  (23): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (24): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (25): LeakyReLU(negative_slope=0.2, inplace=True)
  (26): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (27): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (28): LeakyReLU(negative_slope=0.2, inplace=True)
  (29): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (30): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (31): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (32): LeakyReLU(negative_slope=0.2, inplace=True)
  (33): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)
Traceback (most recent call last):
  File "/content/BDInvert_Release/BDInvert/invert.py", line 278, in <module>
    main()
  File "/content/BDInvert_Release/BDInvert/invert.py", line 176, in main
    basecode_encoder.load_state_dict(torch.load(args.encoder_pt_path)['encoder'])
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by kkang831** [comment]
I think you should check if the pretrained model exists in the proper path. This is an error I have never encountered.

**Comment by loboere** [comment]
I fixed it, the arguments that I put were wrong, but now nothing happens, am I missing something?

!python /content/BDInvert_Release/BDInvert/invert.py --image_list /content/test/test.list --weight_pnorm_term 0.1 --encoder_pt_path /content/BDInvert_Release/BDInvert/pretrained_models/encoder_stylegan2_ffhq1024_basesize16.pth

Building generator for model `stylegan2_ffhq1024` ...
Finish building generator.
Loading StyleGAN checkpoint from `checkpoints/stylegan2_ffhq1024.pth` ...
Finish loading StyleGAN checkpoint.
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/lib/python3.7/dist-packages/lpips/weights/v0.1/vgg.pth
basecode_layer :  x03
Encoder input shape  = [3, 128, 128]
Encoder output shape = torch.Size([512, 16, 16])
StyleGAN BaseCode Encoder Architecture
Sequential(
  (0): Conv2d(3, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): LeakyReLU(negative_slope=0.2, inplace=True)
  (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (5): LeakyReLU(negative_slope=0.2, inplace=True)
  (6): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (7): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (8): LeakyReLU(negative_slope=0.2, inplace=True)
  (9): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (12): LeakyReLU(negative_slope=0.2, inplace=True)
  (13): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (14): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (15): LeakyReLU(negative_slope=0.2, inplace=True)
  (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (17): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (18): LeakyReLU(negative_slope=0.2, inplace=True)
  (19): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (20): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (21): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (22): LeakyReLU(negative_slope=0.2, inplace=True)
  (23): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (24): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (25): LeakyReLU(negative_slope=0.2, inplace=True)
  (26): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (27): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (28): LeakyReLU(negative_slope=0.2, inplace=True)
  (29): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (30): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (31): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (32): LeakyReLU(negative_slope=0.2, inplace=True)
  (33): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)
0it [00:00, ?it/s]

**Comment by loboere** [comment]
I already solved it missing to specify the extension of the images.

!python make_list.py --image_folder /content/test2/ --file_type="jpg"
