### ISSUE TITLE
It seems that this repository lack of stylegan2_runner.

### ISSUE THREAD

**Issue by Tomclancysi** [kkang831/BDInvert_Release#4]
Thank for your great work.

```
 def train_step(self, data, **train_kwargs):
        # Set level-of-details.
        G = self.get_module(self.models['generator'])
        D = self.get_module(self.models['discriminator'])
        Gs = self.get_module(self.models['generator_smooth'])
        G.synthesis.lod.data.fill_(self.lod) # stylegan2 synthesis does't have attribute lod so it raise an Exception
        D.lod.data.fill_(self.lod)
        Gs.synthesis.lod.data.fill_(self.lod)
        ......
```
In stylegan_runner.py , lod is used for ProGAN, but i want to train a stylegan2 model where ProGAN is removed, so this code does not work. So how to train a stylegan2 use code in this repository ?  Maybe a stylegan2_runner is needed.

**Comment by kkang831** [comment]
In fact, the StyleGAN model of this repo was copied from GenForce Lib (https://github.com/genforce/genforce) as it is. So, I think you should contact GenForce.
